### ISSUE TITLE
Мультимедиа для Яндекс Колонки

### ISSUE THREAD

**Issue by Yevgen16** [sergejey/majordomo-nspanel#3]
Добрый день. Сергей, а не планируется продолжения в плане работы для управления Яндекс Колонкой? Что-то типа включения-выключения треков.

**Comment by sergejey** [comment]
Добрый днень.

Непосредственной интеграции с колонкой в модуле не будет, но это, пожалуй, и не задача модуля панели. Т.е. сейчас уже можно создавать элементы типа кнопок, которые будут выполнять методы или сценарии, а в них самих уже имеет смысл реализовывать управление Яндекс.Колонкой.

Ещё панель поддерживает экран типа медиа-карточки (https://docs.nspanel.pky.eu/card-media/) -- но пока я её не добавлял, т.к. не уверен, что оно многим актуально.

**Comment by Yevgen16** [comment]
Да, я и имел ввиду экран типа медиа-карточки. С него и думал, что можно реализовать управление и колонкой, и медиа-проигрывателем.

**Comment by sergejey** [comment]
ок, я попробую на ближайшее время запланировать добавление этой карточки

**Comment by sergejey** [comment]
Я добавил тип экрана cardMedia -- в sample_config можно посмотреть возможности по привязки данных. Но, как я говорил ранее, непосредственно управление колонками надо реализовывать отдельно с помощью привязанных методов или сценариев -- примеров у меня нет, к сожалению, так что с этим необходимо самостоятельно разбираться :)
